// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrTrnLeHZsvu5NlwS5Q8NAUx_5G8wALNQ',
    appId: '1:1063317454163:web:2469af8185cd1d904475a6',
    messagingSenderId: '1063317454163',
    projectId: 'sinauapp-4cb82',
    authDomain: 'sinauapp-4cb82.firebaseapp.com',
    storageBucket: 'sinauapp-4cb82.firebasestorage.app',
    measurementId: 'G-FDWD9WB9J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaq5ZNY-2LIkTYWYxUYH6M5VsZD9QdnUM',
    appId: '1:1063317454163:android:85a371cc92aa211d4475a6',
    messagingSenderId: '1063317454163',
    projectId: 'sinauapp-4cb82',
    storageBucket: 'sinauapp-4cb82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAizl-oMWGyXpncIpG2SRTUnwX4k0WZYbo',
    appId: '1:1063317454163:ios:c03df62563b1d5074475a6',
    messagingSenderId: '1063317454163',
    projectId: 'sinauapp-4cb82',
    storageBucket: 'sinauapp-4cb82.firebasestorage.app',
    iosBundleId: 'com.example.sinauapp',
  );
}
